export const ADD_JOURNAL = "ADD_JOURNAL";
export const ADD_JOURNALS = "ADD_JOURNALS";
export const UPDATE_JOURNAL = "UPDATE_JOURNAL";
export const DELETE_JOURNAL = "DELETE_JOURNAL";
export const JOURNALS_REQUEST = "JOURNALS_REQUEST";
export const JOURNALS_FAILED = "JOURNALS_FAILED";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
